### ISSUE TITLE
for some reason i cant get this to work?

### ISSUE THREAD

**Issue by bath-tub** [qzdl/Samplify#15]
i had to modify readme instructions to be 
```
git clone https://github.com/qzdl/samplify.git && cd samplify && python3 -m venv samplify && source samplify/bin/activate && pip install -r requirements.txt
```

and i couldn't get the application to run ... ? im a python noob 😭 

```
(samplify) (base) bath@millers-mbp samplify % pwd
/Users/bath/github/samplify/src/samplify
(samplify) (base) bath@millers-mbp samplify % 
```

tried `python3 samplify.py` and had a `config.py` in the root directory as well . 

running the file:

```
(samplify) (base) bath@millers-mbp samplify % python3 samplify.py 
Traceback (most recent call last):
  File "/Users/bath/github/samplify/src/samplify/samplify.py", line 2, in <module>
    from samplify.sample_finder import Samplify
  File "/Users/bath/github/samplify/src/samplify/samplify.py", line 2, in <module>
    from samplify.sample_finder import Samplify
ModuleNotFoundError: No module named 'samplify.sample_finder'; 'samplify' is not a package
(samplify) (base) bath@millers-mbp samplify % 
```

**Comment by bath-tub** [comment]
also from root ran `python3 setup.py` and it did some stuff . but not enough to get the project working 😕

**Comment by bath-tub** [comment]
cc @qzdl
